### ISSUE TITLE
Login through different accounts

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#110]
Can only login using a Github account. Will need to change settings when the repository URL changes.

Logging in gives very little benefit, apart from admin actions.

* Facebook: site needs to be live before I can set it up/test. Might still be tricky due to Cambridge Analyticia.
* Twitter: add this as a login option?
* Others: not sure which ones might be of interest. Wordpress.com? Other OAuth providers?

**Comment by peterwebster** [comment]
Given that we've parked the various login-dependent requirements for non-admin users, I see the point here.
My thoughts are these:
(i) if we carry on with just Github login (as the team have these already), that's easy now, but what happens if and when Github change their way of working? This might be an argument for Twitter/Wordpress and others as back-up routes that need no additional dev work.
(ii) whatever we do, we should leave the door open to later implementation of wider OAuth login.

**Comment by peterwebster** [comment]
See also #105

**Comment by peterwebster** [comment]
Leave Wordpress, closing ticket. Testing now under #105
