### ISSUE TITLE
Content bottom #2: reimplement as list of Pages

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#119]
Hi @nomoregrapes :  could you advise how best to do this? It doesn't seem possible to change the kind of widget for one that's already there.
I would do it as hard links (as is the case with the three that are there already) but you then get the underlining.

I think I probably need to remove the widget and add it in again of the right type, but I'm not sure I can then preserve the page layout.

**Comment by nomoregrapes** [comment]
In the options of the widget click "delete" (or drag the widget away to the list of widgets). The 2 bottom areas scale their widths to fit the extra space.

Drag the pages widget from the left into Content Bottom 3.
If you want to specify a specific list(not all pages) then first go to Appearance/Menus and "create new menu" that you can then use in the Nav Menu widget.

Alternatively, you could add a widget and then remove the widget you don't want. All the content areas can have multiple widgets (like the sidebar does), you'll just see it looks ugly on the bottom ones because they won't vertically line-up.

**Comment by peterwebster** [comment]
Done.
