### ISSUE TITLE
Search options in WP

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#120]
We have a choice to make about this, as raised by Julia.

In the Wordpress site, we currently have two sets of search facilities: the drop-down at the top,  which allows all manner of faceted searches of the journal and annotations, but does not cover the WP content. On the right, we *also* have a single search, for the journals alone, and another that searches just the WP content.
http://community.dur.ac.uk/henson.project/ 

There is some duplication here, which is not ideal, so we have three options:
(i) remove the dropdown, which presents the major disadvantage that the navigation options will be very different depending on which part of the site the user is in;
(ii) remove both options on the right hand side, meaning that there is no facility anywhere to search the WP content;
(iii) remove just the 'Search the Journals', which solves all the difficulties in (i) and (ii) but emphasises the fact that there are two search options.
While liking none of them really, I would favour (iii), then (ii) then (i)

? @DurHHHI @nomoregrapes 
Presumably there's no easy way to have a single search which encompasses WP and repository content, or at least not at this late stage.

**Comment by DurHHHI** [comment]
@peterwebster I'm with you on preference hierarchy.

**Comment by nomoregrapes** [comment]
Even with the best wording, I fear people will not know what a search box does until they use it. I prefer (ii) over (iii). However, I'm the outnumbered, and just the developer.

What value does searching the WP "commentaries" add? Are you more likely to search Google or be sent a link to one of the essays. Good menus will direct you to pages like "abbreviations used", when you might not have known what to search for anyway.

(iv) I could add an option to the drop down box at the top, i.e. Everything, journals... "commentaries" (or "essays and help". However only that last option would include WP results. This probably supports the suggestion to rename "Everything" to "Whole Journals" or "Journals & Annotations".

Should the WP option exist when you're on a repository page? Note that "Find on this page" isn't an option when you're on WP, because it wont work.

**Comment by peterwebster** [comment]
Let me think about this for a day or two @nomoregrapes

**Comment by DurHHHI** [comment]
@peterwebster and @nomoregrapes - mentioned preference only - very flexible here and totally defer to the professionals!! ;)

**Comment by nomoregrapes** [comment]
Decided on (iv) Extra drop-down for search will be called "Essays & Help"
Will be on both repository pages & wordpress pages.

**Comment by peterwebster** [comment]
I shall remove the two search options on the right (moving to inactive for now in case they needed to be restored)

**Comment by peterwebster** [comment]
Two search options removed from right of WP page (moved to Inactive Widgets, in case they need to be restored.)

**Comment by nomoregrapes** [comment]
"Essays & Help" search option is now implemented on both Worpress & Repository parts.

**Comment by peterwebster** [comment]
Could @DurHHHI and @KPalmerHeathman test this in the repository part of the site? It's fine in WP

**Comment by KPalmerHeathman** [comment]
Will have a check now, seeing as I'm on campus.

**Comment by KPalmerHeathman** [comment]
Seems to be working fine - searched for 'editorial' using 'essays and help' from the repository, got some results.

**Comment by peterwebster** [comment]
OK, closing this now.
