### ISSUE TITLE
Display of person names in search results

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#131]
In some circumstances, the persons are still showing up as ID numbers in search results.

![image](https://user-images.githubusercontent.com/32575539/42168460-eeb706a6-7e08-11e8-91a2-cb91eac26e34.png)

**Comment by peterwebster** [comment]
Probably just an echo of an older issue showing up under different conditions elsewhere @nomoregrapes

**Comment by nomoregrapes** [comment]
This happens now & then when I'm changing/breaking/fixing things. I have to restart the repository system on my computer, and then it's fixed. So if I noticed, it's usually fixed within 5 minutes (includes 30 seconds of no website at all).

It won't happen when the website is in it's final place, because I'll be more conscious about making changes and if a restart is needed.
