### ISSUE TITLE
Arrange mapping of bought domain name to site

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#150]
For once we're deployed in a final or at least ongoing place @nomoregrapes 

@BoguslawObara was on the case with registering the domain.

**Comment by peterwebster** [comment]
Hih @BoguslawObara : I wonder whether you've had a chance to register the domain?

**Comment by nomoregrapes** [comment]
My steps on what needs to be done.
* Decide the desired domain name (mentioned in e-mails, but calling it domain.com here as these issues are public). - done.
* Register domain.com
* Decide how to use subdomains, could be...
  * Wordpress part, use root domain (i.e. https://domain.com) which will map to http://community.dur.ac.uk/henson.project/ (and anything to the right of the url will match)
  * Repository part, use https://repository.domain.com, or maybe https://journals.domain.com (so https://journals.domain.com/journals will map to http://henson.durham.ac.uk/journals, and https://journals.domain.com/manage will map to http://henson.durham.ac.uk/manage, etc...)
* Contact CIS and explain that's how you want to setup your domain and subdomain. They will need to tell you what nameservers to point to.
* Login to domain registration, and put in those nameserver details.
* It's advised to wait 48 hours for the nameserver setting to take affect for everyone around the world, though it may work for you within in an hour or 2.
* Login to http://community.dur.ac.uk/henson.project/wp-admin and under Settings, General, change the Wordpress and the Site address to http://domain.com
* If CIS have set it up right, the repository won't need any changes because all the links are based on what domain you used to reach it.

**Comment by peterwebster** [comment]
@BoguslawObara Hi Boguslaw: Julia will shortly be in touch about registering the domain, as discussed (she may have done so already). Here's the ticket with Gregory's instructions as to what to with it.

**Comment by peterwebster** [comment]
@nomoregrapes some movement on this, as per email of 20th March, with service reference I190315-0024

**Comment by nomoregrapes** [comment]
Request for configuration sent to CIS.

**Comment by nomoregrapes** [comment]
There's more of a chance it could get done today...
>  Request for Change regarding "Domain changes hensonjournals DNS" was approved on 26-04-2019 10:09.
> 
> Your change will now proceed to the next appropriate implementation stage and a member of the CIS team will be in touch if any additional input is needed from you.

Once they say it's changed,  we can check https://whois.icann.org/en/lookup?name=hensonjournals.org and if the nameserver is still set to DNS0.DUR.AC.UK / DNS1.DUR.AC.UK then the 48-hour-wait is not required.

**Comment by peterwebster** [comment]
I need to check in whose name the domain is registered as @BoguslawObara about to move on.

**Comment by peterwebster** [comment]
Domain is managed within the university, so closing this ticket now.
