### ISSUE TITLE
Clearing a search parameter redirects to WP homepage

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#186]
If I try to remove the Organisations/Wallis facet here, I am redirected to henson-test..... Really, I need to stay on the search page.

https://henson-test.durham.ac.uk/?utf8=%E2%9C%93&search_field=only_organisations&q=Wallis

**Comment by peterwebster** [comment]
Optimal solution: redirects to whichever annotation search type was used: ie, in this case, /organisations

If that's too much at this stage, redirect all of them to https://henson-test.durham.ac.uk/journals

**Comment by nomoregrapes** [comment]
I fixed this before seeing your 2nd comment. Pushed it to test.

I set it to the expected behaviour for Blacklight. If you remove "Wallis" you get the results for all organisations. In the same way if you do a search for [wife, in journals, limited to vol 15](https://henson-test.durham.ac.uk/?f%5Bhas_model_ssim%5D%5B%5D=Journal&f%5Bvolume_sim%5D%5B%5D=15&q=wife&search_field=all_fields) and remove the "wife" facet, you will get results for journals, limited to vol 15.

Let me know if you want to instead change it to how you suggested. It would require me writing out the logic for each of the types.

**Comment by peterwebster** [comment]
This looks great; closing down now. Thanks @nomoregrapes
