### ISSUE TITLE
Next and previous journal entry links

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#197]
![image](https://user-images.githubusercontent.com/32575539/45630727-2cd54a00-ba91-11e8-8657-885ed11e6a38.png)
Sorry to bother you both, but I've tried solving this by myself to no avail. There's a section of Vol 14 where I just cannot get the entries to link together, so I checked in the control sheet and as above, there are 2 entries with the same filename. I'm guessing that's where the problem is, so how can I sort it? Or is it something one of you will need to do, rather than me?

**Comment by peterwebster** [comment]
@KPalmerHeathman do both the files exist, or is one missing (in the repository)?

**Comment by KPalmerHeathman** [comment]
No sign of the entry for the 13th (p. 411).

**Comment by peterwebster** [comment]
Could you start here  https://henson.durham.ac.uk/journals/00-11-12 and work through and see if everything is now in order? If so, close this ticket.  @KPalmerHeathman 

FYI (and @DurHHHI ): if you find that the forward or back links are missing in any journal page, if you Edit, you'll find that the PrevJournal and NewJournal are probably not complete. Fill these in and it should solve the problem,

In this particular case, we had a missing file because there were two lines in the control sheet with the same filename.

**Comment by KPalmerHeathman** [comment]
All good, thanks and closed!
