### ISSUE TITLE
Line and paragraph spacing in WP

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#201]
One of the issues raised is this  http://community.dur.ac.uk/henson.project/index.php/journals/2018/hensons-view-on-things/
I'd welcome your view. @KPalmerHeathman @DurHHHI

**Comment by DurHHHI** [comment]
@peterwebster I have no strong feelings on this. Completely support what you think looks best for the website, and what is feasible to custom within Gregory's limited time. On the question of line space within paragraphs, I agree - I think the spacing looks fine as is.

**Comment by peterwebster** [comment]
@nomoregrapes : in WP, the requirement is to amend the vertical spacing between paragraphs, so that it is larger than at present, but definitely not as large as the double space that is used at  http://community.dur.ac.uk/henson.project/index.php/journals/2018/hensons-view-on-things/  
(I'm assuming the same style is applied to posts and pages.)

**Comment by peterwebster** [comment]
There was also the suggestion that the line spacing within paragraphs is too wide. I incline to disagree and opinion is divided, so we'll park that for now.

**Comment by nomoregrapes** [comment]
If you look at the source of the page, Wordpress seems to deal with typical writers in a good way.
* Single return, creates a line break `<br>`
* Double return, instead of a line break stops the paragraph and starts a new one `</p><p>`

I've reduced the gap between paragraphs(p tags), but left the line break (br) as-is. 

This avoids you having to edit all the content, and reserves the ability for a single return if there is any case you might want to start a new line but not a new paragraph.

**Comment by peterwebster** [comment]
OK: closing this now but cc to @KPalmerHeathman @DurHHHI for information.
