### ISSUE TITLE
Published items showing as unpublished on production

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#218]
Here, I'm not logged in, and am seeing things that I think must therefore be set to publish, but the GUI tells me they are unpublished.

![image](https://user-images.githubusercontent.com/5520710/47206391-6fd05900-d380-11e8-9035-c504cbd07590.png)

![image](https://user-images.githubusercontent.com/5520710/47206427-85458300-d380-11e8-9e6c-e12edbb9743f.png)

**Comment by nomoregrapes** [comment]
**In short:** I'm going to see if a server restart fixes this when I push to production.

**Background**
I think the cause might be related to me returning to work after a period of absence.
My laptop IP address had changed, so I had to restart Solr (on Boguslaw's Helios server) which is used by all servers (dev, test, production). It may be that the Rails server (run by CIS for the library) needs to be restarted after a Solr restart. The test rails server has been deployed since, so restarted. Production hasn't, but it will restart after I deploy later today.

**Comment by peterwebster** [comment]
@nomoregrapes I think this ticket is now dealt with, so closing it now.
