### ISSUE TITLE
Link to New Note from existing

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#220]
For discussion next time (to see how much time there is available) @nomoregrapes : to create an 'Add New Note' option that works in the same way as New Person, New Reference etc.

**Comment by peterwebster** [comment]
Ah, no, found it: so, requirement is to add a link to https://henson.durham.ac.uk/notes/new from the footer of existing ones, to match the other annotation types. @nomoregrapes 

ie. from here  https://henson.durham.ac.uk/notes/note12

**Comment by nomoregrapes** [comment]
Actually, none had the "New" link on the page for a specific annotation, the link is on the type index page i.e.  https://henson.durham.ac.uk/notes/
There isn't a menu link to the Notes page so that's why it's probably not found.

Nevertheless, I've added a "New x" link to those specific annotation pages, for all types (People, Notes,....)

Deployed to test-server, will be on production when we deploy there.

**Comment by peterwebster** [comment]
@nomoregrapes found the link from /notes/note123 to notes/new - that's great, thanks.

But right now there is a 500 error if one tries to create a new note from notes/new. Possibly related to #218

**Comment by peterwebster** [comment]
I created new persons and new places OK, so it would seem that the issue is only with notes/new

**Comment by nomoregrapes** [comment]
Not related to that. This was a typo in the code for creating notes.

Fixed now, and on test-server.

**Comment by peterwebster** [comment]
Great @nomoregrapes this is fine now. Closing ticket.
