### ISSUE TITLE
Issue with date sorting in search results

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#222]
Possibly related to #218, but the date sorting seems to fail here. This was a search using the date picker for the whole of 1900, run from /journals

https://henson.durham.ac.uk/?utf8=%E2%9C%93&search_field=only_journals&q=&start_year=1900&start_month=1&start_day=1&end_year=1900&end_month=12&end_day=31

**Comment by nomoregrapes** [comment]
Technical notes, for me to continue investigating...
* In catalog_controller, the journal date sort is set to `dateFrom_dtsi desc, filename_tesi asc` but should be `dateFrom_dtsim desc, filename_tesim asc` (fields end with m), so it's not looking at any field.
* Correcting the field name typos breaks the search completely with an error along the lines of `can not sort on multivalued field`
* According to the journal models, they are not a multivalued field, but there's possibly some known confusion with Ruby being able unable to tell Solr that a field is multivalued=no. From this point, internet knowledge/answers seem to break down.
* It might need some configuration setting to be done for Solr on Helios(the Solr server) rather than trying to pass it from the Ruby app. Which config file needs to be figured out, and what to setup. It potentially involves the config having to refer to specific field names rather than have lots of wildcard field settings. This can be potentially damaging (make config backups!) and would probably require reindexing Solr after making any change (~40-60 min wait).
* https://groups.google.com/forum/#!msg/blacklight-development/kRl4pwRS_E4/xFZaqPQKDQAJ
* https://github.com/projectblacklight/blacklight/wiki/Configuration---Solr-fields

**Comment by peterwebster** [comment]
Thanks for this @nomoregrapes : we should, I think, set aside a decent length of time for this, as there are several unknowns in this.

**Comment by peterwebster** [comment]
In call with @nomoregrapes agreed to use the ID (derived from the XML file name) as the basis for the date search.

**Comment by peterwebster** [comment]
@DurHHHI @KPalmerHeathman long story, but the repository is having difficulty using the DateTo and DateFrom fields in the control sheets as a means of sorting search results.
Please continue to record them, though, as they are used for other purposes.

For the purposes of the sorting however, you've done us all a favour by adopting a consistent way of composing the file name:

yy-mm-dd for files that cover a single day:
eg, 05-12-24 for 24-Dec-1905

And:  
yy-mm-dd-mm-dd for ranges of dates:
eg. 06-02-04-02-17 for 4-Feb-1906 to 17-Feb-1906

Well done you; pat yourselves on the back, and (from now on) make this a hard and fast rule.

**Comment by nomoregrapes** [comment]
The make-do for journal sorting (using the id field, derived from the filename) is now on test_server.

You might want to keep this issue open, and I'll see if I can make it use DateFrom.

**Comment by peterwebster** [comment]
Many thanks @nomoregrapes : I haven't tested this to destruction, which I will do, but it is a great improvement on what is already on production so we should go ahead with it. Assigning to me now.

**Comment by peterwebster** [comment]
After 18 months of use, no further comments noted on this, so closing the issue.
