### ISSUE TITLE
straight and curly q. marks

### ISSUE THREAD

**Issue by dpl0js** [peterwebster/henson#34]
We agreed that we would use straight q. marks (although I can't remember the reason why!).  Should this policy apply to apostrophes too?

**Comment by DurHHHI** [comment]
Hi Julia,
Peter kindly said that straight or curly quotation marks can be addressed on his end before returning files to us for XML markup. Since Peter's confirmation, Katie and I moved through the remainder of the word transcription file without correcting all quotations marks to straight. I would imagine that, if straight quotations can be addressed via Peter's end, he would be able to do the same with apostrophes.
Hope I'm not speaking out of turn, @peterwebster!

**Comment by williamsonphilip** [comment]
I can't now remember the decision, but this exchange has prompted this (pedantic) thought.  HHH considered himself as a stylist, who cared about how things looked on paper.  I've not seen enough of the text with this in mind, but did his practice vary between straight and curly?  What do we think he intended?   My thought is that he might have intended curly, because was this not the style in the books he used?  Curly is used in his own books.  If we have straight, might we be introducing a practice of modern PCs and printers, which HHH would not have entertained?

**Comment by dpl0js** [comment]
Good point.  Can Hilary or Katie remember why we took this decision?

A comparison between 1902 and 1920 reveals a definite tendency towards curly single q. marks and straight double q. marks.  Apostrophes are slightly more variable, but with more of a tendency towards straight rather than curly.

I can do more research on this (perhaps Katie and Hilary can, too, with the CDs you have copied so far); if it turns out to be a regular pattern do we a) want to stick to it regardless of the occasional deviation or b) follow H. to the letter.

If we choose a), can Peter standardise along these lines?

If H. is more erratic, should we follow him anyway rather than return to a policy of uniformity?

**Comment by peterwebster** [comment]
@dpl0js and I agreed on straight in email correspondence on September 29th (with subject heading 'XML/XSL previewing tool' . My reasoning then was that the straight ones displayed correctly in the editing mockup that @kpalmerheathman and @DurHHHI have, and curled did not (without an additional intervention to code them as Unicode characters), and it was one step fewer to carry out, if it was all the same from an editorial point of view.

Subject to a little more research, I would think that I can probably revise my Stage 2 process in order to code them all formally, so we can have whichever we agree, but make two observations:

(i) there will be some rather dull manual work to do in volume 14 to reflect the change. This I can't automate, unfortunately.
(ii) in general, I would want to advocate having curled in all cases (including apostrophes) or straight in all cases, but not a mixture. The visual effect on screen would be rather unexpected, especially if they occure in close proximity, and the subtlety of Henson's habits lost, since the user would need to begin clicking around the editorial conventions documentation to understand why it was the case. For every reader who did so investigate, I would expect there to be many more who simply thought it was a mistake. I doubt a print publisher would accept such inconsistency were the edition with OUP or some other press.

More broadly, I quite see Philip's point that the straightness is a technological convention, but fidelity to the visual impact of Henson's pages is possible only with either a facsimile edition, or a text edition with page images throughout. I rather feel that we're creating something different.

**Comment by dpl0js** [comment]
Thank you @peterwebster.  Unless Philip has any further qualms, I suggest we stick to plan A and use straight q. marks only (including apostrophes).  Please can you confirm that there is no need to standardise them manually as part of the checking process. 

@KpalmerHeathman and @DurHHHI, once we agree on the form we will use, could you please add a note to Editorial Policies?

**Comment by williamsonphilip** [comment]
OK, yes, we can't achieve an exact facsimile, and what is easiest is a strong argument given the other complications.  Sorry to have re-opened the issue.  Agreed: we can cover this in 'Editorial Policies'.

**Comment by peterwebster** [comment]
@dpl0js straight or curly, there's no need to make any changes in Word, as I standardise during Stage 2.

Very happy to stick with straight quotations (personally, I prefer them on screen), but I make just one additional observation: if we are at all ambivalent about it, it is possible to opt for curly now and change to straight later (with the revision work incurred in volume 14); it will be quite impossible at a later date to change straight to curly (because the distinction between left and right-orientation will have been lost.)

**Comment by peterwebster** [comment]
Note to self:  https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html

**Comment by dpl0js** [comment]
Resolved then; straight q. marks throughout.  Thanks to all, Julia
