### ISSUE TITLE
request for advice

### ISSUE THREAD

**Issue by dpl0js** [peterwebster/henson#40]
@williamsonphilip please can you confirm that a [sic] sign is needed in the middle of this sentence.  Henson may have lost the verb after 'in order to' in copying it out.  But if it makes sense to you, then I will delete sic.  I have checked the transcription several times.

If I could see that there was any inherent necessity for a Virgin Birth in order to the Incarnation, [sic] or that there was an obvious conspicuousness in it, or that religious and moral interests were properly at stake in it, I think personally I should waive the critical question, & advance from agnosticism to such a measure of assent as that kind of inferential belief implies. [237] [symbol]

**Comment by williamsonphilip** [comment]
Yes, it looks to me as if some indication is needed.  If [sic], this should come before the comma, but I think this might be a case where we should have '.... for a Virgin Birth in order to [word missing] the Incarnation, ...'.   I think raise this at tomorrow's meeting, as a matter to that might go into 'Editorial policies'.

**Comment by dpl0js** [comment]
Thank you - [word missing]. We will make more use of this and analogous phrases, and will draw it to the attention of K and H tomorrow.

**Comment by peterwebster** [comment]
@dpl0js may I close this ticket now, if a course of action is agreed?
