### ISSUE TITLE
Static pages of person/place annotations

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#53]
This is the first in a series of small decisions I'll be asking you to make before Gregory arrives. This one concerns the short notes on people, places, organisations, that are being compiled.

The primary way in which a user accesses these is via a mention of that person/place in a particular daily entry, at which point they can most likely read the annotation in some sort of pop-up box.

Users will also have access to a person/place/organisation 'search', in which the list of names (without descriptions) is used as a means of pulling out all daily entries that mention a person.

My question is whether we also need a static page(s) in which all the accounts of persons/places are given in alphabetical order.

I tend to think not, since the user is unlikely to come to the site seeking information about the persons in the journal: they either need information in its context (the pop-ups) or to search for a name. I don't think we need treat this information in the same way as we would with the list of Henson's writings, secondary and primary sources, abbreviations, editorial notes, interpretative essay etc.

I would welcome your feedback.

@williamsonphilip @dpl0js @KPalmerHeathman @DurHHHI

**Comment by williamsonphilip** [comment]
Thanks Peter.  Yes I agree.  For the reasons you state, I don't think a static page for persons/places/etc. is needed.

**Comment by dpl0js** [comment]
I agree too: no need for a static page.

**Comment by peterwebster** [comment]
Many thanks @dpl0js @williamsonphilip : I think we've agreed that we do not need a static page for persons, places, organisations. 

May I sum up what I think we're heading towards as regards the means by which users access the information that is being compiled. We have five kinds of information (persons, places, organisations, sermons/speeches, publications), and three means of engaging with them: via a popup embedded within a single daily entry; via a search (based on an index compiled using the markup); via a static listing in alphabetical order.

Persons:  popup & search
Places:  popup & search
Organisations: popup & search
Sermons/speeches: popup only
Publications: popup and static list (Henson's only), and search (?)

I would welcome feedback on the last two, as we haven't discussed them in much detail. At the moment, @KPalmerHeathman and @DurHHHI are not finding very many sermons and speeches to markup, and I doubt the value of indexing them for search, or of a static page for these.

On publications, we are marking up both Henson's publications and those of others that he cites. I think we clearly require a static list of Henson's works, possibly selected rather than exhaustive, but do we also want to allow users to search for them ? For just Henson's works, or his sources too?

**Comment by peterwebster** [comment]
I wonder if @dpl0js and @williamsonphilip have a moment to consider the matter in the comment above.

**Comment by dpl0js** [comment]
Thank you Peter,  I agree that the first three matters are now settled, to everybody's satisfaction.

On sermons, and speeches, I would be prepared to limit references to pop-up form only, although with some reluctance, given the difficulty of anticipating future usage of the edition.  I'm not sure whether the problem is lack of sermons (clearly not) or difficulty in\lack of time for tracing published forms or repositories.  Could we delay a decision on this question until next Wednesday, when we have our first project meeting?

It is alright with me to confine Henson's publications to pop-up and static form only.  I would think that the publications of others can be safely limited to pop-up form only.

**Comment by peterwebster** [comment]
Many thanks @dpl0js for this. Of course, do by all means discuss it in the meeting next week. Two observations:

1. On sermons and speeches: we can easily enable any of the three options, and disable one or more later. What we can't do is decide against something now, and then enable it later. So, if in doubt we should err on the inclusive side.

2. On publications: when dealing with Henson's, you may wish to consider enabling search for the most prominent ones only (major books, not letters to the Times), whilst listing all of them in the static page. Again, we can do this, but should settle on it now.

**Comment by dpl0js** [comment]
Thank you Peter, I will put this to the committee next week.

**Comment by williamsonphilip** [comment]
Dear Peter,

Apologies for a delayed reply.  Suffice to say, I agree with Julia.

To expand a little: a valuable scholarly contribution would be to have a complete (static) bibliography of (a) Henson's books; and of the contents, where these are collections of sermons and lectures (with dates of delivery if possible); (b) articles in reviews and The Bishoprick (some of which will also be in the books).

Ideally, it would be good to extend this with a list of HH's surviving sermons, adding to those published in the books those which were published journals or reviews and newspapers, and the unpublished ones in the collection of his papers in the Cathedral.  But maybe this is too large a task?

I agree that letters to The Times are problematic, in part because they are so numerous - but also because these might only only be part of his published 'letter to editors'.  I am not sure how well we could chase up letters to other newspapers and journals.  

Perhaps it would be wise for Katie or Hilary to keep basic notes on sermons and letters, and review the position later?

Best wishes,
Philip
________________________________________

**Comment by dpl0js** [comment]
Thank you Philip, it seems a shame to miss the opportunity of collecting Henson's sermons, if only those to which we are led by the journals.  I have added this to the list of discussion points for next Wednesday.  As Peter says, we can start off compiling a static list and search facilities for such outputs and see how it goes.
Peter and I can discuss in our next phone call the constraints on a search facility for letters to The Times, which I will then pass on.

**Comment by peterwebster** [comment]
As I think this has now been concluded in conversation, and expressed in the requirements documents, closing this ticket.
