### ISSUE TITLE
Search drop-down ordering

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#63]
On the master search page, there is a drop-down allowing the user to select a particular kind of search. I suggest that the options are as follows (in this order):

All Journals [first, and default]
Persons
Places
Organisations
Publications
Sermons & speeches
All Fields

It's a moot point whether the default should be All Journals, or All Fields (and this is across all views in the GUI, isn't it, and not just in the main Search view?) It's another thing to discuss on 22/5, and (I guess) easy enough to change.

**Comment by peterwebster** [comment]
See this Twitter poll  https://twitter.com/pj_webster/status/989089111133876224

**Comment by peterwebster** [comment]
Hi @nomoregrapes if this is done, could you just stick a screenshot in here, then I can close the ticket?

**Comment by peterwebster** [comment]
To confirm: default behaviour is all fields, unless in Journals/People etc pages.

**Comment by peterwebster** [comment]
See also #74

**Comment by nomoregrapes** [comment]
I forgot, how this actually works:
It does a search, limiting the type if desired, on all fields in it's list.

If you search for only refs/publications, it will consider the narrative field (although it won't because refs don't have a narrative field) it will also consider title, subtitle, etc.
So the list of fields considered is now `content_tesim firstName_tesim lastName_tesim narrative_tesim author_tesim title_tesim subtitle_tesim volumeDetails_tesim periodicalDetails_tesim`

A special case is that 'issues/controversies' for journals, and 'keywords' for events are only found in an "Everything" search. They've been done as a special "Topic" type, that uses the title_tesim field.


This ticket seemed to be concerned with the unseen parts of the search, but it's very closely couple with visuals so I'll continue discussion in #74, and close the discussion here.
