### ISSUE TITLE
Next page/previous page links which span volume ends

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#79]
As sort key is discontinuous between volumes, amend links that cross journals ends.

**Comment by nomoregrapes** [comment]
Annoyingly, this is going to require a reimport of all the journals (due to a mistake how sort keys were stored).
When editing a journal entry, you can specify the next and prev journals (to override the sort key). This allows me to get [v14 back matter](http://10.245.28.108:3000/journals/V14_backmatter) to link to v15 (and the reverse) without having to do the reimport.

Note to self: make sure journals_controller `@journal.sortKey.to_i - 1` is updated after reimporting with changed data type. (use commented code).

I'll aim to do a full empty of the database and reingest w/c 18th June. Let's keep this ticket open until then, so I remember to test for that.

**Comment by peterwebster** [comment]
@nomoregrapes yes, let's do that.

**Comment by peterwebster** [comment]
Me to resolve #90 before doing this.

**Comment by peterwebster** [comment]
Issue #90 now resolved. Before a new ingest, @nomoregrapes needs a fresh copy of the control sheet to v15, now on OneDrive > Master Data > Control Files.

**Comment by nomoregrapes** [comment]
Greg to test this again. Might be an overwritten bit for vol15_front

**Comment by nomoregrapes** [comment]
I've found the problem.
* The first time you ingest a journal entry it now gets the linking right.
* You have the option to manually overwrite links, in-case sortKey isn't how you want.
* When you do an ingest that updates a journal entry, it won't check the links because it doesn't want to undo any manual links you put in.

Because this went wrong earlier, I've done a special update reingest of volume 14 and I'm doing it for volume 15 now. I'll be able to close this ticket when I get in on Monday morning.

**Comment by nomoregrapes** [comment]
All linking is fixed and working for future ingests.
